### ISSUE TITLE
Frontend Development

### ISSUE THREAD

**Issue by jpalazz2** [BinghamtonCoRE/bikeshare#11]
@alanplotko @adamnieto You two pretty much have total control over what's going on with this. Even just static pages with no backend integration right now would be cool. I can work on getting that done once you get something up for us to play with.

I think for now a simple index page and perhaps an admin page would be a good start.

**Comment by alanplotko** [comment]
I'm going to try getting this set up on my laptop right now.

**Comment by jpalazz2** [comment]
If you already have an idea of what the layouts might look like I'd suggest closing this issue and opening one for each page. Tag them with the help wanted so we know which ones need people.

**Comment by alanplotko** [comment]
I'll close this once the configuration on the back and the initial pages on the front are set up, since that's what this issue is aiming to resolve.

We'll create issues down the line for each page when we find it necessary to bring in other people.
