### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jpalazz2** [BinghamtonCoRE/bikeshare#12]
We'll need to make sure there's good documentation going forward. I think @hallfox was looking into some stuff to add into the sourcecode. Maybe somebody could start up a wiki to help keep track as well? Or maybe that's too much...

**Comment by hallfox** [comment]
Yes, the popular documentation suite is [Sphinx](http://www.sphinx-doc.org/en/stable/), and I figure we'd just
use that to generate the documentation wiki.

On Wed, Mar 30, 2016 at 1:00 PM, Joseph Palazzolo notifications@github.com
wrote:

> We'll need to make sure there's good documentation going forward. I think
> @hallfox https://github.com/hallfox was looking into some stuff to add
> into the sourcecode. Maybe somebody could start up a wiki to help keep
> track as well? Or maybe that's too much...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BinghamtonCoRE/bikeshare/issues/12

## 

// Taylor Foxhall

**Comment by jpalazz2** [comment]
That link tho ಠ_ಠ

[Sphinx](http://www.sphinx-doc.org/en/stable/)

**Comment by alanplotko** [comment]
Wow, I couldn't even fix that link. What happened there? ._.

**Comment by hallfox** [comment]
So Sphinx will auto generate documentation based off of restructured text source files, but we may need to ask ourselves if we need a full wiki for our models.

**Comment by alanplotko** [comment]
Just a quick mention for future visitors: see #32 for discussion on potentially moving away from Sphinx.
