### ISSUE TITLE
Database needs to be set up

### ISSUE THREAD

**Issue by hallfox** [BinghamtonCoRE/bikeshare#31]
We need a legitimate way of inserting, deleting, querying, etc from the database. It will also be really helpful for when we start writing more interesting tests.

**Comment by jpalazz2** [comment]
This would be through the mongoengine models weve setup in models.py no? Unless you want a wrapper around those.

**Comment by hallfox** [comment]
I'm just figuring we'll need a better way to setup a database at will, a wrapper would probably help. Unless I'm misunderstanding how powerful the models are.

**Comment by jpalazz2** [comment]
Well in theory, no DB access would take place without one of the models between it. You can add and delete through the models.

**Comment by jpalazz2** [comment]
```
ross = User(email='ross@example.com', first_name='Ross', last_name='Lawley').save()
```

or with attribute syntax

```
ross = User(email='ross@example.com')
ross.first_name = 'Ross'
ross.last_name = 'Lawley'
ross.save()
```
