### ISSUE TITLE
Do we really need Sphinx if we just maintain a wiki?

### ISSUE THREAD

**Issue by hallfox** [BinghamtonCoRE/bikeshare#32]
So sphinx will generate documentation for a huge library and it's used by just about everyone, but we're not developing any libraries, so I think a short reference about what our endpoints and models do would be sufficient. If you all agree, I can open a pull request to delete the doc/ directory and remove Sphinx from requirements.txt

**Comment by jpalazz2** [comment]
I was also thinking that as well. We're not gonna have some monolithic API or anything. I think the wiki is more suited to this project since we're just looking to document what it is/what it does.

**Comment by alanplotko** [comment]
Wiki is our best bet. Sphinx looks great for large libraries and APIs. We're not in the process of making either.
