### ISSUE TITLE
Port over BUBS website's content

### ISSUE THREAD

**Issue by alanplotko** [BinghamtonCoRE/bikeshare#39]
@adamnieto and I were informed that we need to pull the BUBS website's contents into the app. It's essentially a copy-paste job, having pages that match theirs. It's all static content (e.g. about, faq, etc.)

@adamnieto, you already started this, so can you see to it that it's done? Thanks!

**Comment by jpalazz2** [comment]
You'll probably have to add an "about" page for this

**Comment by alanplotko** [comment]
They want all of the content, not just about.

**Comment by adamnieto** [comment]
I will get on this!

**Comment by alanplotko** [comment]
This issue is resolved by #43. We need to review the pull request.

Update: Merged #43. Closing.
